In [1]:
### whether there is any significant difference in the diameter of the cutlet between two units.

In [2]:
import seaborn as sns
import scipy as sp
import pandas as pd
import numpy as np
import scipy.stats as stats
df=pd.read_csv("C:/Users/khann/OneDrive/Desktop/excel r assignments/Cutlets.csv")
df.head()


Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [3]:
df.values

array([[6.809 , 6.7703],
       [6.4376, 7.5093],
       [6.9157, 6.73  ],
       [7.3012, 6.7878],
       [7.4488, 7.1522],
       [7.3871, 6.811 ],
       [6.8755, 7.2212],
       [7.0621, 6.6606],
       [6.684 , 7.2402],
       [6.8236, 7.0503],
       [7.393 , 6.881 ],
       [7.5169, 7.4059],
       [6.9246, 6.7652],
       [6.9256, 6.038 ],
       [6.5797, 7.1581],
       [6.8394, 7.024 ],
       [6.597 , 6.6672],
       [7.2705, 7.4314],
       [7.2828, 7.307 ],
       [7.3495, 6.7478],
       [6.9438, 6.8889],
       [7.156 , 7.422 ],
       [6.5341, 6.5217],
       [7.2854, 7.1688],
       [6.9952, 6.7594],
       [6.8568, 6.9399],
       [7.2163, 7.0133],
       [6.6801, 6.9182],
       [6.9431, 6.3346],
       [7.0852, 7.5459],
       [6.7794, 7.0992],
       [7.2783, 7.118 ],
       [7.1561, 6.6965],
       [7.3943, 6.578 ],
       [6.9405, 7.3875]])

In [4]:
val=stats.chi2_contingency(df)
val

(0.4542834311598112,
 1.0,
 34,
 array([[6.81625543, 6.76304457],
        [7.00077565, 6.94612435],
        [6.84958552, 6.79611448],
        [7.07210406, 7.01689594],
        [7.32910721, 7.27189279],
        [7.12686782, 7.07123218],
        [7.07596915, 7.02073085],
        [6.88823639, 6.83446361],
        [6.98938118, 6.93481882],
        [6.96413263, 6.90976737],
        [7.16496653, 7.10903347],
        [7.4906377 , 7.4321623 ],
        [6.87172193, 6.81807807],
        [6.50719911, 6.45640089],
        [6.89581597, 6.84198403],
        [6.95886205, 6.90453795],
        [6.65808806, 6.60611194],
        [7.3797549 , 7.3221451 ],
        [7.32348526, 7.26631474],
        [7.07627033, 7.02102967],
        [6.9434519 , 6.8892481 ],
        [7.31756214, 7.26043786],
        [6.55347975, 6.50232025],
        [7.25541959, 7.19878041],
        [6.90424889, 6.85035111],
        [6.92538137, 6.87131863],
        [7.14267954, 7.08692046],
        [6.82579265, 6.77250735],
        [6.66486

In [5]:
#Observed Values
Observed_Values = df.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[6.809  6.7703]
 [6.4376 7.5093]
 [6.9157 6.73  ]
 [7.3012 6.7878]
 [7.4488 7.1522]
 [7.3871 6.811 ]
 [6.8755 7.2212]
 [7.0621 6.6606]
 [6.684  7.2402]
 [6.8236 7.0503]
 [7.393  6.881 ]
 [7.5169 7.4059]
 [6.9246 6.7652]
 [6.9256 6.038 ]
 [6.5797 7.1581]
 [6.8394 7.024 ]
 [6.597  6.6672]
 [7.2705 7.4314]
 [7.2828 7.307 ]
 [7.3495 6.7478]
 [6.9438 6.8889]
 [7.156  7.422 ]
 [6.5341 6.5217]
 [7.2854 7.1688]
 [6.9952 6.7594]
 [6.8568 6.9399]
 [7.2163 7.0133]
 [6.6801 6.9182]
 [6.9431 6.3346]
 [7.0852 7.5459]
 [6.7794 7.0992]
 [7.2783 7.118 ]
 [7.1561 6.6965]
 [7.3943 6.578 ]
 [6.9405 7.3875]]


In [6]:
Expected_Values=val[3]
Expected_Values

array([[6.81625543, 6.76304457],
       [7.00077565, 6.94612435],
       [6.84958552, 6.79611448],
       [7.07210406, 7.01689594],
       [7.32910721, 7.27189279],
       [7.12686782, 7.07123218],
       [7.07596915, 7.02073085],
       [6.88823639, 6.83446361],
       [6.98938118, 6.93481882],
       [6.96413263, 6.90976737],
       [7.16496653, 7.10903347],
       [7.4906377 , 7.4321623 ],
       [6.87172193, 6.81807807],
       [6.50719911, 6.45640089],
       [6.89581597, 6.84198403],
       [6.95886205, 6.90453795],
       [6.65808806, 6.60611194],
       [7.3797549 , 7.3221451 ],
       [7.32348526, 7.26631474],
       [7.07627033, 7.02102967],
       [6.9434519 , 6.8892481 ],
       [7.31756214, 7.26043786],
       [6.55347975, 6.50232025],
       [7.25541959, 7.19878041],
       [6.90424889, 6.85035111],
       [6.92538137, 6.87131863],
       [7.14267954, 7.08692046],
       [6.82579265, 6.77250735],
       [6.66486451, 6.61283549],
       [7.34421618, 7.28688382],
       [6.

In [7]:
no_of_rows=len(df.iloc[0:2,0])
no_of_columns=len(df.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [8]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [9]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 0.45428343115981107


In [10]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [11]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.5003078089115751
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.5003078089115751


In [12]:
observed_chi_val = p_value
#if observed chi-square < critical chi-square, then variables are not related
#if observed chi-square > critical chi-square, then variables are not independent (and hence may be related).
print('Interpret by critical value')
if observed_chi_val <= critical_value:
    # observed value is not in critical area therefore we accept null hypothesis
    print ('Null hypothesis cannot be rejected (variables are not related)')
else:
    # observed value is in critical area therefore we reject null hypothesis
    print ('Null hypothesis cannot be excepted (variables are not independent)')

Interpret by critical value
Null hypothesis cannot be rejected (variables are not related)


In [13]:
##Inference: As (p_value=0.500) > (α = 0.05); Accept Null Hypothesis i.e. μ1 = μ2 ( Thus, there is no difference in diameters of cutlets between two unit

In [14]:
## Question 2 : To find the buyers ratio between male and female in different regions.

In [15]:
ratio=df=pd.read_csv("C:/Users/khann/OneDrive/Desktop/excel r assignments/BuyerRatio.csv")
ratio

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [16]:
alpha=0.05
Male = [50,142,131,70]
Female=[435,1523,1356,750]
Sales=[Male,Female]
print(Sales)

[[50, 142, 131, 70], [435, 1523, 1356, 750]]


In [17]:
chiStats = sp.stats.chi2_contingency(Sales)
print('Test t=%f p-value=%f' % (chiStats[0], chiStats[1]))
if chiStats[1] < 0.05:
  print('we reject null hypothesis')
else:
  print('we accept null hypothesis')

Test t=1.595946 p-value=0.660309
we accept null hypothesis


In [18]:
alpha = 0.05
critical_value = sp.stats.chi2.ppf(q = 1 - alpha,df=chiStats[2])

print('critical_value:',critical_value)
# Find the critical value for 95% confidence*
                      #degree of freedom

observed_chi_val = chiStats[0]
#if observed chi-square < critical chi-square, then variables are not related
#if observed chi-square > critical chi-square, then variables are not independent (and hence may be related).
print('Interpret by critical value')
if observed_chi_val <= critical_value:
    # observed value is not in critical area therefore we accept null hypothesis
    print ('Null hypothesis cannot be rejected (variables are not related)')
else:
    # observed value is in critical area therefore we reject null hypothesis
    print ('Null hypothesis cannot be excepted (variables are not independent)')

critical_value: 7.814727903251179
Interpret by critical value
Null hypothesis cannot be rejected (variables are not related)


In [19]:
##Inference : proportion of male and female across regions is same